
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module PCM_Top(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_DIN,
	input 		          		ADC_DOUT,
	output		          		ADC_SCLK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output reg       [6:0]		HEX0,
	output reg	     [6:0]		HEX1,
	output reg       [6:0]		HEX2,
	output reg	     [6:0]		HEX3,
	output reg		 [6:0]		HEX4,
	output reg		 [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

wire rst;
  wire [1:0] curr_mode;
  wire pdm_in1, pdm_in2;
  wire data_val; 
  wire [15:0] mic1_pcm, mic2_pcm, mic3_pcm, mic4_pcm;

  assign pdm_in1 = data_val ? GPIO[1] : 1'b0;
  assign pdm_in2 = data_val ? GPIO[2] : 1'b0;

  // Active high synchronous reset.
  assign rst = ~KEY[0];

  // We don't care about the remaining GPIO pins.
  assign GPIO[35:3] = 32'hzzzz;

  // Instatiate the Audio Front End.
  Audio_Front_End iAUD_FRONT (
      .clk_i(CLOCK_50),
      .rst_i(rst),
      .mode_req_i(SW[1:0]),

      .ADC_data_out_i(ADC_DOUT),
      .ADC_SCLK_o(ADC_SCLK),
      .ADC_CS_o(ADC_CONVST),
      .ADC_data_in_o(ADC_DIN),

      .curr_mode_o(curr_mode),
      .data_val_o (data_val),
      .mic_clk_o  (GPIO[0])
  );

  pdm_to_pcm_no_bp iPDM_PCM_1 (
    .clk(CLOCK_50),
    .mic_clk(GPIO[0]),
    .mic_mode(curr_mode),
    .rst_n(~rst),
    .mic_raw(pdm_in1),
    .pcm_pos(mic1_pcm),
    .pcm_neg(mic2_pcm)
  );

  pdm_to_pcm_no_bp iPDM_PCM_2 (
    .clk(CLOCK_50),
    .mic_clk(GPIO[0]),
    .mic_mode(curr_mode),
    .rst_n(~rst),
    .mic_raw(pdm_in2),
    .pcm_pos(mic3_pcm),
    .pcm_neg(mic4_pcm)
  );

  // Drive Mode (HEX0) manually
  always @(*) begin
    HEX0 = 7'b1111111;
    HEX1 = 7'b1111111;
    HEX2 = 7'b1111111;
    HEX3 = 7'b1111111;
    HEX4 = 7'b1111111;
    HEX5 = 7'b1111111;

    case (curr_mode)
      2'b00: HEX0 = 7'b1000000;  // 0
      2'b01: HEX0 = 7'b1111001;  // 1
      2'b10: HEX0 = 7'b0100100;  // 2
      2'b11: HEX0 = 7'b0110000;  // 3
      default: begin
        HEX0 = 7'b1111111;
        HEX1 = 7'b1111111;
        HEX2 = 7'b1111111;
        HEX3 = 7'b1111111;
        HEX4 = 7'b1111111;
        HEX5 = 7'b1111111;
      end
    endcase
  end

endmodule
