
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SDRAM_Test(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// KEY //////////
	input 		     [3:0]		KEY
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire								sdram_ctrl_clk;
wire								readdatavalid;
wire [2:0]                          addr;
wire                                read;
wire [15:0]                         readdata;


rom_intf intf (
                 .clk(CLOCK_50),
				 .rst_n(KEY[0]),
				 .readdatavalid(readdatavalid),
				 .addr(addr),
				 .read(read)
              );

mem_wrapper mem (
					.clk(CLOCK_50),
					.reset_n(KEY[0]),
					
					// Avalon-MM slave interface
					.address(addr),
					.read(read),
					.readdata(readdata),
					.readdatavalid(readdatavalid),
					.waitrequest(),
					.state()
				);
												
sdram_pll 			u6	(
							.refclk(CLOCK_50),
							.rst(1'b0),
							.outclk_0(sdram_ctrl_clk),
							.outclk_1(DRAM_CLK)

						   );


//SDRam Read and Write as Frame Buffer
Sdram_Control	   u7	(	//	HOST Side						
						   .RESET_N(KEY[0]),
							.CLK(sdram_ctrl_clk),

							//	FIFO Write Side 1
							.WR1_DATA(readdata),
							.WR1(readdatavalid),
							.WR1_ADDR(0),
                            .WR1_MAX_ADDR(8),
						    .WR1_LENGTH(8'h01),
		                    .WR1_LOAD(~KEY[0]),
							.WR1_CLK(CLOCK_50),

							// disable write port 2
							.WR2_DATA(16'h0000),
							.WR2(1'b0),
							.WR2_ADDR(0),
							.WR2_MAX_ADDR(0),
							.WR2_LENGTH(8'd0),
							.WR2_LOAD(~KEY[0]),
							.WR2_CLK(CLOCK_50),

							// disable read port 1
							.RD1_DATA(),
							.RD1(1'b0),
							.RD1_ADDR(0),
							.RD1_MAX_ADDR(0),
							.RD1_LENGTH(8'd0),
							.RD1_LOAD(~KEY[0]),
							.RD1_CLK(CLOCK_50),

							// disable read port 2
							.RD2_DATA(),
							.RD2(1'b0),
							.RD2_ADDR(0),
							.RD2_MAX_ADDR(0),
							.RD2_LENGTH(8'd0),
							.RD2_LOAD(~KEY[0]),
							.RD2_CLK(CLOCK_50),
										
							//	SDRAM Side
						   .SA(DRAM_ADDR),
							.BA(DRAM_BA),
							.CS_N(DRAM_CS_N),
							.CKE(DRAM_CKE),
							.RAS_N(DRAM_RAS_N),
							.CAS_N(DRAM_CAS_N),
							.WE_N(DRAM_WE_N),
							.DQ(DRAM_DQ),
							.DQM({DRAM_UDQM,DRAM_LDQM})
						   );




endmodule
