import os
import sys
import re
import json
import config
import subprocess
from pathlib import Path
from log_utils import check_logs
from collections import defaultdict

"""
Utility functions for compiling SystemVerilog files and managing dependencies.
These functions are used to determine which files need recompilation,
compile the necessary files, and check for compilation errors or warnings.
"""


def collect_files(graph, test_name, post_synth):
    """
    Collects files in DFS order from the dependency graph.

    Args:
        graph (dict): The dependency graph.
        test_name (str): The name of the testbench.
        post_synth (bool): Flag indicating whether to run post-synthesis simulation.    
    
    Returns:
        list: Ordered list of module names in DFS order.
    """
    # Maintain visited set and ordered list.
    visited = set()
    ordered = []

    def dfs(node):
        """
        Depth-First Search to collect nodes in order.

        Args:
            node (str): Current node being visited.
        
        Returns:
            None
        """
        # If already visited, return.
        if node in visited:
            return
        
        # Mark the node as visited.
        visited.add(node)

        # Get the entry for the current node.
        entry = graph[node]

        # STOP DFS HERE if post_synth and gate_file exists.
        if post_synth and entry.get("gate_file"):
            ordered.append(node)
            return

        # Otherwise, continue normal DFS by visiting instantiated children.
        for child in entry["instantiates"]:
            if child in graph:
                dfs(child)

        # Append the current node to the ordered list after visiting children.
        ordered.append(node)

    # Start DFS from the top-level testbench.
    dfs(test_name)

    # Return the ordered list of modules.
    return ordered


def make_f_file(test_name, post_synth):
    """
    Generates the .f file for the specified testbench.

    Args:
        test_name (str): The name of the testbench.
        post_synth (bool): Flag indicating whether to run post-synthesis simulation.
    
    Returns:
        str: Path to the generated .f file.
    """
    # Load the graph.
    with open(config.DEPENDENCY_GRAPH, 'r') as f:
        graph = json.load(f)
    
    # Get the files required for the testbench, including dependencies in DFS order.
    dependencies = collect_files(graph, test_name, post_synth)

    # Lists to hold package, interface, and other files separately.
    package_files = []
    interface_files = []
    other_files = []

    # Iterate through the dependencies and categorize them.
    for name in dependencies:
        # Get the entry for the current dependency from the graph.
        entry = graph[name]

        # Categorize package files.
        if entry["type"] == "package":
            if entry["rtl_file"]:
                package_files.append(entry["rtl_file"])
            continue

        # Categorize interface files.
        if entry["type"] == "interface":
            if entry["rtl_file"]:
                interface_files.append(entry["rtl_file"])
            continue

        # Categorize non-package modules.
        if post_synth and entry["gate_file"]:
            other_files.append(entry["gate_file"])
        elif entry["rtl_file"]:
            other_files.append(entry["rtl_file"])

    # Ensure interfaces are always compiled even when not explicitly present
    # in module instantiation edges (interface usage is often type-based).
    for _, entry in graph.items():
        if entry.get("type") == "interface" and entry.get("rtl_file"):
            interface_files.append(entry["rtl_file"])

    # Deduplicate while preserving order.
    ordered_files = package_files + interface_files + other_files
    file_list = list(dict.fromkeys(ordered_files))

    # Write the collected files to the .f file.
    f_file_path = os.path.join(config.BUILD_DIR, f"{test_name}.f")
    with open(f_file_path, "w") as f:
        f.write(
            "# ======================================================================\n"
            "# THIS FILE IS AUTOMATICALLY GENERATED — DO NOT EDIT MANUALLY\n"
            "#\n"
            "# Purpose:\n"
            "#   This .f file lists Verilog/SystemVerilog source files in the order\n"
            "#   required for compilation by the simulator.\n"
            "#\n"
            "# Notes:\n"
            "#   - Changes to this file will be overwritten.\n"
            "#   - This file should NOT be checked into version control (git).\n"
            "#   - Source files are discovered and ordered by the build script.\n"
            "# ======================================================================\n\n"
        )

        for file in file_list:
            f.write(file + "\n")
    
    # Return the path to the generated .f file.
    return f_file_path


def get_f_file(test_name, post_synth):
    """
    Returns the path to the dependency map file (.f file) of the requested testbench.

    Args:
        test_name (str): The name of the testbench.
        post_synth (bool): Flag indicating whether to run post-synthesis simulation.

    Returns:
        str: Path to the .f file.
    """
    # Grab the .f file path within the build directory for the specified test.
    f_file = os.path.join(config.BUILD_DIR, f"{test_name}.f")

    # Check if the .f file exists before returning.
    if os.path.isfile(f_file):
        return f_file
    else:
        # If the .f file does not exist, generate it using the make_f_file function.
        return make_f_file(test_name, post_synth)
    

def get_files_to_compile(f_file, log_file):
    """
    Determine which .v files need recompilation based on the existence and 
    timestamps of the compilation log file and the source .v files.

    Args:
        f_file (str): Path to the .f file containing the list of .v/.vg/.sv files.
        log_file (str): Path to the compilation log file.

    Returns:
        str: A space-separated string of .v files that need recompilation.
    """
    # This function reads the .f file and returns a list of all .v/.sv/.vg files.
    def parse_f_file(f_file):
        """
        This function reads the .f file and returns a list of all .v/.sv/.vg files.

        Args:
            f_file (str): Path to the .f file.

        Returns:
            list: List of .v/.sv/.vg file paths.      
        """
        # Read the .f file and collect all .v/.sv/.vg files.
        files = []

        # Open and read the .f file line by line.
        with open(f_file, "r") as f:
            # Iterate through each line in the .f file.
            for line in f:
                # Strip whitespace from the line.
                line = line.strip()

                # Skip empty lines and comments.
                if not line or line.startswith("#") or line.startswith("//"):
                    continue

                # Add .v, .sv, and .vg files to the list.
                files.append(line)
        
        # Return the list of collected files.
        return files
    
    # Check if the log file exists or if it contains errors.
    if not os.path.exists(log_file) or check_logs(log_file, "c") == "error":
        # Return all files for recompilation.        
        return f_file  

    # Initialize an empty string to hold files needing recompilation.
    files_to_recompile = ""
    
    # Parse the .f file to get all .v/.sv/.vg files.
    all_files = parse_f_file(f_file)
    
    # Get the modification timestamp of the log file.
    log_file_mtime = os.path.getmtime(log_file)

    # Compare the modification time of each .v file to the log file's timestamp.
    for v_file in all_files:
        if os.path.getmtime(v_file) > log_file_mtime:
            # If the .v file is newer than the log file, mark it for recompilation.
            files_to_recompile += v_file + " "

    # Return the list of files needing recompilation.
    return files_to_recompile


def compile_files(test_name, args):
    """
    Compile the required files for the test simulation.

    This function checks if recompilation is needed by calling `get_files_to_compile`.
    If no recompilation is needed, it exits without performing compilation.

    Args:
        test_name (str): The name of the testbench file to be compiled.
        args (argparse.Namespace): Command-line arguments, including flags to modify behavior.

    Raises:
        SystemExit: If compilation fails, the program exits with an error.
    """
    # Path to the compilation log file.
    log_file = os.path.join(config.COMPILATION_DIR, f"{test_name}_compilation.log")

    # Get the .f file for the testbench.
    f_file = get_f_file(test_name, args.post_synth or test_name.endswith("ps_tb"))

    # Determine the files that need recompilation.
    compile_inputs = get_files_to_compile(f_file, log_file)

    # If no files need recompilation, exit without performing compilation.
    if not compile_inputs:
        return
        
    # Begin compilation process.
    try:
        # Check if the work library exists.
        work_dir = f"./tests/WORK/{test_name}"
        work_exists = Path(work_dir).is_dir()

        # If the file ends with .f, use the -f option for vlog.
        use_f = compile_inputs.endswith(".f")

        # Base vlog arguments.
        vlog_args = "+acc -stats=none"

        # If post synthesis is requested compile with the timescale directive.
        if args.post_synth or test_name.endswith("ps_tb"):
            vlog_args = f"-timescale=1ns/1ps {vlog_args}"

        # Append file inputs to the vlog command.
        if use_f:
            vlog_args = f"{vlog_args} -f {compile_inputs}"
        else:
            vlog_args = f"{vlog_args} {compile_inputs}"

        # Check if the work library exists, and compile accordingly.
        if not work_exists:
            compile_command = (
                f"vsim -c -logfile {log_file} -do "
                f"'vlib {work_dir}; "
                f"vlog {vlog_args} -work {work_dir}; "
                f"quit -f;'"
            )
        else:
            compile_command = (
                f"vlog {vlog_args} -logfile {log_file} -work {work_dir}"
            )
        
        # Execute the compilation command.
        subprocess.run(compile_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    except subprocess.CalledProcessError as e:
        if args.all:
            print(f"{test_name}: Compilation failed with error {e.returncode}. Run 'make log c' for details. {e.stderr.decode('utf-8')}.")
        else:
            # Print log file contents in case of an error when running a single test.
            with open(log_file, 'r') as log_fh:
                print("\n===== Compilation failed with the following errors =====\n")
                print(log_fh.read())
        sys.exit(1)
    
    # Check the log file for warnings or errors.
    result = check_logs(log_file, "c")
    if result == "warning":
        print(f"{test_name}: Compilation completed with warnings. Run 'make log c' for details.")
    elif result == "error":
        if args.all:
            print(f"{test_name}: Compilation has errors. Run 'make log c' for details.")
        else:
            # Print log file contents in case of an error when running a single test.
            with open(log_file, 'r') as log_fh:
                print("\n===== Compilation failed with the following errors =====\n")
                print(log_fh.read())
        sys.exit(1)


def find_files():
    """
    Finds and returns all Verilog-related source files within a phase directory.

    This function recursively searches the 'designs', 'tests', and 'packages'
    subdirectories under the given phase path and collects all files with
    .v, .sv, or .vg extensions.

    Returns:
        list[str]: Sorted list of full paths to all matching Verilog files.
    """
    # Subdirectories to search within the phase directory.
    # interfaces/ is optional and included only when present.
    dirs = [config.DESIGNS_DIR, config.TESTS_DIR, config.PACKAGES_DIR, config.INTERFACES_DIR]

    # List to store discovered file paths.
    files = []

    # Iterate through each target subdirectory.
    for d in dirs:
        # Skip if the directory does not exist.
        if not os.path.isdir(d):
            continue

        # Walk the directory tree recursively.
        for r, _, fnames in os.walk(d):
            for fn in fnames:
                # Check for Verilog/SystemVerilog file extensions and append to the list.
                if fn.lower().endswith(('.v', '.sv', '.vg')):
                    files.append(os.path.abspath(os.path.join(r, fn)))

    # Return files in deterministic (sorted) order.
    return sorted(files)


def classify_file_by_path(file_path):
    """
    Classifies a Verilog file as 'package', 'testbench', or 'design' based on its path.
    
    Args:
        file_path (str): The full path to the Verilog file.
    
    Returns:
        str: The classification of the file ('package', 'testbench', or 'design').
    """
    # Get the relative path from the test directory.
    rel = os.path.relpath(file_path, config.TEST_DIR).replace("\\", "/")

    # Convert to lowercase for case-insensitive comparison.
    low = rel.lower()

    # Classify based on path patterns and return the appropriate type.
    if '/packages/' in low or low.startswith('packages/'):
        return 'package'
    elif '/interfaces/' in low or low.startswith('interfaces/'):
        return 'interface'
    elif os.path.basename(low).endswith('_tb.sv') or os.path.basename(low).endswith('_tb.v'):
        return 'testbench'
    else:
        return 'design'


def build_dependency_graph():
    """
    Builds a module-centric dependency graph for a given directory.

    This function:
      1. Scans designs/, tests/, and packages/ for .v, .sv, and .vg files
      2. Detects module and package definitions
      3. Detects module instantiations and package imports
      4. Produces a flat JSON graph keyed by module/package name
      5. Records RTL and gate-level file paths separately
      6. Records which modules/packages each module depends on

    The output JSON is written to build/dependency_graph.json by default.
    """
    # Matches module definitions. For example: 'module my_module (...);'.
    MODULE_DEF_RE = re.compile(r'^\s*module\s+([A-Za-z_]\w*)', re.MULTILINE)

    # Matches package definitions. For example: 'package my_package;'.
    PACKAGE_DEF_RE = re.compile(r'^\s*package\s+([A-Za-z_]\w*)', re.MULTILINE)

    # Matches interface definitions. For example: 'interface my_if (...);'.
    INTERFACE_DEF_RE = re.compile(r'^\s*interface\s+([A-Za-z_]\w*)', re.MULTILINE)

    # Matches module instantiations. For example: 'my_module u1 (...);'
    MODULE_INST_RE = re.compile(
        r'^\s*(?!module\b)(?!endmodule\b)(?!interface\b)(?!endinterface\b)(?!package\b)(?!endpackage\b)'
        r'(?!modport\b)(?!else\b)(?!begin\b)(?!end\b)(?!if\b)(?!for\b)(?!while\b)(?!case\b)'
        r'(?!always\b)(?!always_ff\b)(?!always_comb\b)(?!always_latch\b)(?!assign\b)(?!task\b)(?!function\b)'
        r'([A-Za-z_]\w*)\s*(?:#\([^)]*\))?\s+[A-Za-z_]\w*\s*(?:\[[^\]]*\])?\s*\(.*?\)\s*;',
        re.MULTILINE | re.DOTALL
    )

    # Matches package import statements. For example: 'import my_package::*;'.
    IMPORT_RE = re.compile(r'^\s*import\s+([A-Za-z_]\w*)\s*::\*\s*;', re.MULTILINE)

    # Output the dependency graph to build/dependency_graph.json by default.
    out_file = config.DEPENDENCY_GRAPH

    # Find all .v/.sv/.vg files under designs/, tests/, and packages/ in the current phase directory.
    all_files = find_files()

    # ------------------------------------------------------------------
    # DATA STRUCTURES USED THROUGHOUT THE FUNCTION
    # ------------------------------------------------------------------
    # Map: module_name -> The RTL source file (.v/.sv) that it defines it.
    module_rtl = defaultdict(list)

    # Map: module_name -> The gate-level source files (.vg) that defines it.
    module_gate = defaultdict(list)

    # Map: package_name -> file path where the package is defined.
    package_defs = {}

    # Map: interface_name -> file path where the interface is defined.
    interface_defs = {}

    # Map: file_path -> entire contents of the file (this avoids reopening files during the second pass).
    file_content_cache = {}

    # ------------------------------------------------------------------
    # FIRST PASS
    #   - Read each file once
    #   - Cache its contents
    #   - Record module definitions
    #   - Record package definitions
    # ------------------------------------------------------------------
    for file_path in all_files:
        try:
            # Open the file safely (ignore encoding issues).
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                file_text = f.read()

            # Store the file contents so we can parse it again later.
            file_content_cache[file_path] = file_text

        except Exception as e:
            # If a file cannot be read, warn and skip it
            print(f"Could not read {file_path}: {e}.")
            continue

        # Extract the file extension (.v, .sv, or .vg).
        file_ext = os.path.splitext(file_path)[1].lower()

        # Find every module definition in this file.
        for module_name in MODULE_DEF_RE.findall(file_text):

            # If the module is defined in .v or .sv, treat it as RTL.
            if file_ext in ('.v', '.sv'):
                module_rtl[module_name].append(file_path)

            # If the module is defined in .vg, treat it as gate-level
            elif file_ext == '.vg':
                module_gate[module_name].append(file_path)

        # Find every package definition in this file
        for package_name in PACKAGE_DEF_RE.findall(file_text):
            # Store the defining file for this package (if duplicated, last one wins — duplicates are not expected).
            package_defs[package_name] = file_path

        # Find every interface definition in this file.
        for interface_name in INTERFACE_DEF_RE.findall(file_text):
            # Store the defining file for this interface.
            interface_defs[interface_name] = file_path

    # ------------------------------------------------------------------
    # DUPLICATE DEFINITION CHECKS (DIAGNOSTIC ONLY)
    # ------------------------------------------------------------------
    # Identify RTL modules defined in more than one file
    duplicate_rtl_modules = [
        module for module, files in module_rtl.items()
        if len(files) > 1
    ]

    # Identify gate-level modules defined in more than one file
    duplicate_gate_modules = [
        module for module, files in module_gate.items()
        if len(files) > 1
    ]

    # Print warnings if duplicates are found
    if duplicate_rtl_modules:
        print("Duplicate RTL module definitions found:")
        for module in duplicate_rtl_modules:
            print("   ", module, ":", module_rtl[module])

    if duplicate_gate_modules:
        print("Duplicate gate-level module definitions found:")
        for module in duplicate_gate_modules:
            print("   ", module, ":", module_gate[module])

    # ------------------------------------------------------------------
    # SECOND PASS
    #   - For each file:
    #       * Detect instantiated modules
    #       * Detect imported packages
    # ------------------------------------------------------------------
    # Map: file_path -> list of module names instantiated in that file.
    file_instantiates = defaultdict(list)

    # Map: file_path -> list of package names imported in that file.
    file_imports = defaultdict(list)

    # Iterate over cached file contents.
    for file_path, file_text in file_content_cache.items():

        # Temporary list of instantiated module names.
        instantiated_modules = []

        # Scan for module instantiations using regex.
        for match in MODULE_INST_RE.finditer(file_text):

            # Append the instantiated module name to the list.
            instantiated_modules.append(match.group(1))

        # Deduplicate and sort the instantiated module list.
        file_instantiates[file_path] = sorted(set(instantiated_modules))

        # Find all imported package names.
        imported_packages = IMPORT_RE.findall(file_text)

        # Deduplicate and sort imported package names.
        file_imports[file_path] = sorted(set(imported_packages))

    # ------------------------------------------------------------------
    # BUILD FINAL MODULE-CENTRIC GRAPH
    # ------------------------------------------------------------------
    # Final graph: module/package name -> metadata dictionary.
    graph = {}

    # Collect every logical entity name (modules + packages).
    all_entity_names = (
        set(module_rtl.keys()) |
        set(module_gate.keys()) |
        set(package_defs.keys()) |
        set(interface_defs.keys())
    )

    # Process each entity in deterministic (sorted) order.
    for entity_name in sorted(all_entity_names):

        # Get RTL file path if it exists.
        rtl_file = module_rtl[entity_name][0] if module_rtl.get(entity_name) else None

        # Get gate-level file path if it exists.
        gate_file = module_gate[entity_name][0] if module_gate.get(entity_name) else None

        # Get package definition file if this is a package.
        package_file = package_defs.get(entity_name)

        # Get interface definition file if this is an interface.
        interface_file = interface_defs.get(entity_name)

        # Choose which file to inspect for dependencies either RTL or package definition.
        defining_file = rtl_file or package_file or interface_file

        # Initialize empty dependency list.
        dependencies = []

        # If a defining file exists, extract its dependencies.
        if defining_file:

            # Add all instantiated modules from this file.
            dependencies.extend(
                file_instantiates.get(defining_file, [])
            )

            # Treat imported packages as dependencies as well.
            for pkg in file_imports.get(defining_file, []):
                if pkg in all_entity_names:
                    dependencies.append(pkg)

        # Remove duplicates while preserving order
        dependencies = sorted(dict.fromkeys(dependencies))

        # Determine entity type (design vs. package vs. testbench)
        if entity_name in package_defs:
            entity_type = "package"
        elif entity_name in interface_defs:
            entity_type = "interface"
        else:
            source_path = rtl_file or gate_file
            entity_type = classify_file_by_path(source_path)

        # Create the graph entry for this module/package
        graph[entity_name] = {
            "type": entity_type,

            # Path to RTL file (if any).
            "rtl_file": (
                defining_file if defining_file else None
            ),

            # Path to gate-level file (if any).
            "gate_file": (
                gate_file if gate_file else None
            ),

            # List of modules/packages this entity depends on.
            "instantiates": dependencies
        }

    # ------------------------------------------------------------------
    # WRITE OUTPUT JSON
    # ------------------------------------------------------------------
    # Write the graph dictionary to disk as pretty-printed JSON.
    with open(out_file, 'w') as json_file:
        json.dump(graph, json_file, indent=2)
