import os
import re
import sys
import config
import argparse
from pathlib import Path
from datetime import date
from dataclasses import dataclass
from file_utils import choose_from_list

"""
This script generates starter Verilog/SystemVerilog files for RTL design and testbench development.

The workflow is intentionally optimized to reduce user typing:
- Module name is the only commonly required input.
- Both DUT and testbench starters are generated by default.
"""


# ==========================================================
# Data model
# ==========================================================
@dataclass
class Port:
    """
    Normalized port metadata container.

    Attributes:
        direction (str): Port direction from DUT perspective (input/output/inout).
        data_type (str): Signal type (typically logic).
        width (str): Optional width text without brackets (for example, 31:0).
        name (str): Port name.
        desc (str): Optional short comment for generated code readability.
    """

    direction: str
    data_type: str
    width: str
    name: str
    desc: str = ""


# ==========================================================
# Argument parsing helpers
# ==========================================================
def parse_arguments():
    """
    Parse command-line arguments for starter generation.

    Returns:
        argparse.Namespace: Parsed command-line options controlling generation
            kind and overwrite mode.
    """
    parser = argparse.ArgumentParser(description="Generate DUT/testbench starter files.")

    # Main generation knobs.
    parser.add_argument(
        "-k",
        "--kind",
        type=str,
        default="both",
        choices=["design", "testbench", "both"],
        help="Starter type to generate (default: both)",
    )

    # Parse and return all options.
    return parser.parse_args()


def normalize_kind(kind):
    """
    Normalize starter kind text into internal values.

    Args:
        kind (str): Kind text from arguments.

    Returns:
        str: One of "design", "testbench", or "both".
    """
    # Map synonyms to canonical values.
    if kind == "design":
        return "design"
    if kind == "testbench":
        return "testbench"

    # Default to generating both files.
    return "both"


# ==========================================================
# Input parsing + project selection helpers
# ==========================================================
def normalize_port_name(name, direction):
    """
    Normalizes port names by appending direction-based suffixes.

    Naming convention:
    - input  -> *_i
    - output -> *_o

    If the name already has the expected suffix, it is returned unchanged.

    Args:
        name (str): Raw signal name entered by user.
        direction (str): Port direction ("input" or "output").

    Returns:
        str: Direction-normalized signal name.
    """
    # Map direction to expected suffix.
    suffix = "_i" if direction == "input" else "_o" if direction == "output" else ""

    # Append suffix only if it is missing.
    if suffix and not name.endswith(suffix):
        return f"{name}{suffix}"

    # Return original name when already normalized.
    return name


def normalize_port_width(width_text):
    """
    Converts user width text into msb:lsb format.

    Supported user width formats:
    - N       -> converted to N-1:0 (example: 12 -> 11:0)
    - msb:lsb -> preserved as-is

    Args:
        width_text (str): Width string entered by user.

    Returns:
        str: Normalized width text (without brackets), or empty for scalar.

    Raises:
        ValueError: If width format is invalid.
    """
    # Handle empty width as scalar.
    if not width_text:
        return ""

    raw = width_text.strip()

    # Convert integer width into msb:lsb form.
    if re.fullmatch(r"\d+", raw):
        width = int(raw)
        if width <= 0:
            raise ValueError(f"Width must be > 0, got '{raw}'.")
        if width == 1:
            return ""
        return f"{width - 1}:0"

    # Accept pre-formatted msb:lsb width.
    if re.fullmatch(r"\d+:\d+", raw):
        return raw

    # Reject unsupported formats.
    raise ValueError(f"Invalid width '{width_text}'. Use N or msb:lsb.")


def choose_design_extension():
    """
    Prompt user to choose DUT file extension.

    Returns:
        str: "sv" or "v".
    """
    # Keep prompting until user selects a supported extension.
    while True:
        choice = input("Design file extension [.sv/.v] (No response is treated as sv): ").strip().lower()

        # Use SystemVerilog as default when user presses Enter.
        if choice == "":
            return "sv"

        # Accept either with or without dot.
        if choice in {"sv", ".sv"}:
            return "sv"
        if choice in {"v", ".v"}:
            return "v"

        # Enter loop again on invalid input.
        print("Invalid extension entered. Please Enter '.sv' or '.v'.")


def make_header_banner(header_label, block_name, description):
    """
    Build hardware-guide-style header comment banner.

    Args:
        header_label (str): Header key label ("Module" or "Testbench").
        block_name (str): Module/testbench identifier shown in the header.
        description (str): Summary text for the module/testbench.

    Returns:
        list[str]: Header lines ready to prepend to generated source.
    """
    # Fill default metadata to match the hardware development guide template.
    clean_desc = description.strip() if description else "TODO"
    author = os.environ.get("USER", "TODO")
    today = date.today().strftime("%m-%d-%Y")

    # Compose standardized guide-style header block.
    lines = [
        "// ------------------------------------------------------------",
        f"// {header_label}: {block_name}",
        f"// Description: {clean_desc}",
        f"// Author: {author}",
        f"// Date: {today}",
        "// ------------------------------------------------------------",
    ]
    
    # Return header lines to be included at the top of generated source files.
    return lines


def parse_ports_compact(raw_ports, direction):
    """
    Parse compact one-line port specification format for one direction.

    Supported token forms (comma-separated):
      name
      name:width
      type:name
      type:name:width

    Example:
      pipe,valid:1,signed:delta:12

    Args:
        raw_ports (str): Raw compact text entered by user.
        direction (str): Direction inferred from prompt context.

    Returns:
        list[Port]: Parsed and validated ports in original order.

    Raises:
        ValueError: If a token is malformed or contains invalid type/name/width.
    """
    # Return empty list when user skips port entry.
    ports = []
    if not raw_ports:
        return ports

    # Validate direction from caller.
    if direction not in {"input", "output", "inout"}:
        raise ValueError(f"Invalid direction '{direction}'. Expected 'input', 'output', or 'inout'.")

    # Split into individual tokens and parse each token independently.
    for token in [text.strip() for text in raw_ports.split(",") if text.strip()]:
        parts = [part.strip() for part in token.split(":")]

        # Initialize defaults.
        data_type = "logic"
        width = ""
        name = ""

        # Form 1: name
        if len(parts) == 1:
            name = parts[0]

        # Form 2: name:width OR type:name
        elif len(parts) == 2:
            left = parts[0]
            right = parts[1]

            # If right side is width-like, parse as name:width.
            if re.fullmatch(r"\d+(:\d+)?", right):
                name = left
                width = normalize_port_width(right)
            else:
                # Otherwise parse as type:name.
                data_type = left if left else "logic"
                name = right

        # Form 3: type:name:width
        elif len(parts) == 3:
            data_type = parts[0] if parts[0] else "logic"
            name = parts[1]
            width = normalize_port_width(parts[2])

        # Any other form is invalid.
        else:
            raise ValueError(
                f"Invalid port token '{token}'. Use name, name:width, type:name, or type:name:width."
            )

        # Validate type syntax.
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", data_type):
            raise ValueError(f"Invalid signal type '{data_type}' in '{token}'.")

        # Validate identifier syntax.
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            raise ValueError(f"Invalid signal name '{name}'.")

        # Apply naming convention based on direction prompt.
        normalized_name = normalize_port_name(name, direction)

        # Append normalized port entry.
        ports.append(Port(direction=direction, data_type=data_type, width=width, name=normalized_name))

    # Return parsed port list.
    return ports


def render_design_template(module_name, description, ports, use_nettype_guard):
    """
    Generate DUT starter source text.

    Args:
        module_name (str): DUT module name.
        description (str): Header description text.
        ports (list[Port]): Ordered list of DUT ports.
        use_nettype_guard (bool): Emit default_nettype guard only for Verilog (.v) output.

    Returns:
        str: Full design source text for the starter DUT file.
    """
    # Start with optional nettype guard and header banner.
    lines = []
    if use_nettype_guard:
        lines.extend(["`default_nettype none // Set the default as none to avoid errors", ""])
    lines.extend(make_header_banner("Module", module_name, description))

    # Emit module declaration with ports when provided.
    if ports:
        lines.append(f"module {module_name} (")

        # Emit each port with optional width and comment.
        for idx, port in enumerate(ports):
            comma = "," if idx < len(ports) - 1 else ""
            width = f"[{port.width}] " if port.width else ""
            comment = f" // {port.desc}" if port.desc else ""
            lines.append(f"    {port.direction} {port.data_type} {width}{port.name}{comma}{comment}")

        lines.append(");")
    else:
        # Support empty stub modules for fast kickoff.
        lines.append(f"module {module_name}();")

    # Add structured placeholder sections in existing repository style.
    lines.extend(
        [
            "",
            "  ///////////////////////////////////",
            "  // Declare any internal signals //",
            "  /////////////////////////////////",
            "",
            "  ////////////////////////////////////////////////////////",
            "  // Implement the module logic as structural/dataflow //",
            "  //////////////////////////////////////////////////////",
            "",
            "  // Add module internals here.",
            "",
            "endmodule",
        ]
    )

    # Close nettype guard only when enabled for .v output.
    if use_nettype_guard:
        lines.extend(["", "`default_nettype wire // Reset default behavior at the end"])

    # Return final source content.
    return "\n".join(lines) + "\n"


def render_testbench_template(module_name, description, ports):
    """
    Generate testbench starter source text.

    The generated testbench includes required final status reporting hooks:
    - YAHOO!! All tests passed.
    - ERROR: <count> test(s) failed.

    Args:
        module_name (str): DUT module name (testbench is module_name + _tb).
        description (str): Header description text.
        ports (list[Port]): DUT port metadata used for TB signal declarations and port mapping.

    Returns:
        str: Full starter testbench source text.
    """
    # Derive testbench module name from DUT module name.
    testbench_name = f"{module_name}_tb"

    # Emit header and TB declaration.
    lines = []
    lines.extend(make_header_banner("Testbench", testbench_name, description))
    lines.append(f"module {testbench_name}();")
    lines.append("")

    # Track test failures through a common error counter.
    lines.append("  int error_count;")
    lines.append("")

    # Emit signal declaration section.
    lines.extend(
        [
            "  ///////////////////////////",
            "  // Stimulus of type logic //",
            "  /////////////////////////",
        ]
    )

    # Declare TB signals for DUT ports.
    if ports:
        for port in ports:
            width = f"[{port.width}] " if port.width else ""
            comment = f" // {port.desc}" if port.desc else ""
            lines.append(f"  logic {width}{port.name};{comment}")
    else:
        # Provide examples when no ports are defined yet.
        lines.append("  // logic clk_i;")
        lines.append("  // logic rst_n_i;")

    # Emit DUT instantiation block.
    lines.extend(
        [
            "",
            "  //////////////////////",
            "  // Instantiate DUT //",
            "  ////////////////////",
            f"  {module_name} iDUT (",
        ]
    )

    # Add named port mappings.
    if ports:
        for idx, port in enumerate(ports):
            comma = "," if idx < len(ports) - 1 else ""
            lines.append(f"    .{port.name}({port.name}){comma}")

    lines.append("  );")

    # Emit starter simulation flow with required pass/fail messages.
    lines.extend(
        [
            "",
            "  initial begin",
            "    error_count = 0;",
            "    // TODO: Initialize inputs.",
            "    // TODO: Apply stimulus and checks.",
            "",
            "    if (error_count == 0) begin",
            "      $display(\"YAHOO!! All tests passed.\");",
            "    end else begin",
            "      $display(\"ERROR: %0d test(s) failed.\", error_count);",
            "    end",
            "",
            "    $stop();",
            "  end",
            "",
            "  ///////////////////////////////////////////////",
            "  // Optional clock generation for synchronous DUT //",
            "  ///////////////////////////////////////////////",
            "  // always",
            "  //   #5 clk = ~clk;",
            "",
            "endmodule",
        ]
    )

    # Return final source content.
    return "\n".join(lines) + "\n"


def find_dut_file(module_name):
    """
    Finds the DUT source file in the designs directory.

    Search order:
    1. <DESIGNS_DIR>/<module_name>.sv
    2. <DESIGNS_DIR>/<module_name>.v

    Args:
        module_name (str): DUT module name.

    Returns:
        Path | None: Path to the DUT file if found, else None.
    """
    # Try common SystemVerilog/Verilog file extensions.
    candidates = [
        Path(config.DESIGNS_DIR) / f"{module_name}.sv",
        Path(config.DESIGNS_DIR) / f"{module_name}.v",
    ]

    # Return the first existing candidate.
    for candidate in candidates:
        if candidate.exists():
            return candidate

    # Return None when no matching DUT file exists.
    return None


def extract_dut_description(dut_path):
    """
    Extracts the DUT description from header comments.

    Expected header pattern:
      // Description: <text>

    Args:
        dut_path (Path): Path to DUT source file.

    Returns:
        str: Extracted description text, or empty if not found.
    """
    # Read DUT file text.
    text = dut_path.read_text(encoding="utf-8", errors="ignore")

    # Search for hardware-guide-style description line.
    match = re.search(r"^\s*//\s*Description:\s*(.+?)\s*$", text, flags=re.MULTILINE)

    # Return matched description if present.
    if match:
        return match.group(1).strip()

    # Fallback: inspect initial comment block above module declaration.
    module_start = re.search(r"^\s*module\b", text, flags=re.MULTILINE)
    header_text = text[: module_start.start()] if module_start else text

    # Collect meaningful comment lines from header block.
    comment_lines = []
    for raw_line in header_text.splitlines():
        stripped = raw_line.strip()
        if not stripped.startswith("//"):
            continue

        # Remove comment markers/decorative slashes.
        content = stripped.lstrip("/").strip().rstrip("/").strip()
        if not content:
            continue
        if set(content) <= {"-", "_", "/", "*"}:
            continue

        comment_lines.append(content)

    # Prefer line text after "filename:" pattern when available.
    for line in comment_lines:
        if ":" in line:
            candidate = line.split(":", 1)[1].strip().rstrip("/").strip()
            if candidate:
                return candidate

    # Otherwise use the first meaningful comment line.
    if comment_lines:
        return comment_lines[0]

    # Return empty string when no description is found.
    return ""


def make_testbench_description(module_name, dut_description):
    """
    Builds a testbench description string from DUT metadata.

    Args:
        module_name (str): DUT module name.
        dut_description (str): DUT description text extracted from source.

    Returns:
        str: Testbench description text.
    """
    # If DUT description is available, include it in TB description.
    if dut_description:
        return f"Verifies {module_name} behavior based on DUT description: {dut_description}"

    # Fallback when DUT description is unavailable.
    return f"Verifies {module_name} behavior."


def parse_ports_from_dut(module_name, dut_path):
    """
    Parse port declarations from DUT module header.

    This parser targets inline module-header declarations such as:
      input logic [11:0] pipe_i,
      output logic valid_o

    Args:
        module_name (str): DUT module name.
        dut_path (Path): Path to DUT source file.

    Returns:
        list[Port]: Parsed DUT ports (input/output/inout).
    """
    # Parse a declaration body into (data_type, width, [names]).
    def parse_decl_body(decl_body):
        """
        Parse one direction declaration body.

        Examples:
          logic [15:0] A, B
          logic signed [31:0] out_data
          wire valid
        """
        # Remove trailing separators and normalize whitespace.
        body = decl_body.strip().rstrip(",").rstrip(";").strip()
        if not body:
            return None

        # Split comma-separated names/declarations.
        chunks = [chunk.strip() for chunk in body.split(",") if chunk.strip()]
        if not chunks:
            return None

        # Parse first chunk as full declaration: "<type/width> <name>".
        first_match = re.match(r"^(.*\S)\s+([A-Za-z_][A-Za-z0-9_]*)$", chunks[0])
        if not first_match:
            return None

        type_width_text = first_match.group(1).strip()
        names = [first_match.group(2).strip()]

        # Parse remaining chunks; they are usually bare names in Verilog declarations.
        for chunk in chunks[1:]:
            # Accept plain names.
            if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", chunk):
                names.append(chunk)
                continue

            # Also accept repeated "<type/width> <name>" forms.
            extra_match = re.match(r"^(.*\S)\s+([A-Za-z_][A-Za-z0-9_]*)$", chunk)
            if extra_match:
                names.append(extra_match.group(2).strip())

        # Extract width token from declaration type.
        width = ""
        width_match = re.search(r"\[(.*?)\]", type_width_text)
        if width_match:
            width = width_match.group(1).strip()
            type_width_text = (
                type_width_text[: width_match.start()] + type_width_text[width_match.end() :]
            ).strip()

        # Use logic as default type when missing.
        data_type = type_width_text if type_width_text else "logic"
        return data_type, width, names

    # Read DUT source lines.
    lines = dut_path.read_text(encoding="utf-8", errors="ignore").splitlines()

    # Track parser state while walking the target module.
    in_target_module = False
    in_header_ports = False
    parsed_ports = []

    for line in lines:
        # Strip inline comments and whitespace.
        code = line.split("//", 1)[0].strip()
        if not code:
            continue

        # Find module declaration first.
        if not in_target_module:
            if re.match(rf"^\s*module\s+{re.escape(module_name)}\b", code):
                in_target_module = True

                # Determine if module uses ANSI header port declarations.
                in_header_ports = "(" in code and not re.search(r"\)\s*;", code)
            continue

        # Stop once target module ends.
        if re.match(r"^\s*endmodule\b", code):
            break

        # Track end of ANSI header declaration list.
        if in_header_ports and re.search(r"\)\s*;", code):
            in_header_ports = False
            continue

        # Parse direction declarations from both styles:
        # - ANSI style inside module header.
        # - Non-ANSI style after header, before internal logic.
        decl_match = re.match(r"^(input|output|inout)\s+(.+)$", code)
        if not decl_match:
            continue

        direction = decl_match.group(1)
        decl_body = decl_match.group(2)
        parsed = parse_decl_body(decl_body)
        if parsed is None:
            continue

        data_type, width, names = parsed

        # Expand multi-name declarations into individual Port entries.
        for signal_name in names:
            parsed_ports.append(
                Port(
                    direction=direction,
                    data_type=data_type,
                    width=width,
                    name=signal_name,
                )
            )

    # Return all parsed ports in declaration order.
    return parsed_ports


def select_project_dir():
    """
    Resolve the target project directory used for starter output.

    Resolution order:
      1. Auto-select when exactly one valid project exists.
      2. Interactive list selection when multiple projects exist.

    Returns:
        str: Absolute path of selected project directory.

    Raises:
        FileNotFoundError: If no valid projects are found.
    """
    # Discover valid project directories using shared config helper.
    project_dirs = config.get_top_level_dirs()

    # Guard against missing project directories.
    if not project_dirs:
        raise FileNotFoundError(
            f"No valid project directories found in '{config.ROOT_DIR}'. "
            f"Expected each directory to contain: {', '.join(config.REQUIRED_SUBDIRS)}."
        )

    # Auto-select for single-project repositories.
    if len(project_dirs) == 1:
        return project_dirs[0]

    # Prompt user to choose one directory from the list.
    return choose_from_list(
        files=project_dirs,
        pre_prompt="Available directories (no default selection):",
        prompt=f"Choose directory (1-{len(project_dirs)}, Enter has no default): ",
    )


# ==========================================================
# Output generation helpers
# ==========================================================
def write_file(path_obj, content):
    """
    Write generated source content to file.

    Args:
        path_obj (Path): Output file path.
        content (str): Generated source text.
        force (bool): Overwrite existing file when True.

    Returns:
        bool: True when file is written, False when skipped.
    """
    # Skip existing files unless --force is enabled.
    if path_obj.exists():
        print(f"Skipped existing file: {path_obj}")
        return False

    # Ensure destination directory exists.
    path_obj.parent.mkdir(parents=True, exist_ok=True)

    # Write output content with UTF-8 encoding.
    path_obj.write_text(content, encoding="utf-8")

    # Inform user of generated file.
    print(f"Generated: {path_obj}")
    return True


def build_outputs(module_name, kind, description, ports, tb_description=None, design_ext="sv"):
    """
    Build the list of output files and rendered content.

    Args:
        module_name (str): DUT module name.
        kind (str): Starter kind ('design', 'testbench', or 'both').
        description (str): Description used for DUT header banner.
        ports (list[Port]): Parsed port list for DUT/TB generation.
        design_ext (str): DUT extension ("sv" or "v") when DUT is generated.

    Returns:
        list[tuple[Path, str]]: Output path and rendered source text pairs.
    """
    # Accumulate generation tasks in deterministic order.
    tasks = []

    # Generate DUT output when requested.
    if kind in {"design", "both"}:
        design_file = f"{module_name}.{design_ext}"
        design_path = Path(config.DESIGNS_DIR) / design_file
        design_text = render_design_template(
            module_name=module_name,
            description=description,
            ports=ports,
            use_nettype_guard=(design_ext == "v"),
        )
        tasks.append((design_path, design_text))

    # Generate testbench output when requested.
    if kind in {"testbench", "both"}:
        tb_base = f"{module_name}_tb"
        tb_file = f"{tb_base}.sv"
        tb_path = Path(config.TESTS_DIR) / tb_file
        tb_text = render_testbench_template(
            module_name=module_name,
            description=tb_description if tb_description else f"Verifies {module_name} behavior.",
            ports=ports,
        )
        tasks.append((tb_path, tb_text))

    # Return collected generation tasks.
    return tasks


# ==========================================================
# Main workflow
# ==========================================================
def main():
    """
    Main entry point for starter generation workflow.

    Workflow:
      1. Parse command-line arguments.
      2. Resolve and setup target project directory.
      3. Resolve module name and generation kind.
      4. Parse optional compact port list.
      5. Render and write DUT/testbench starter files.

    Returns:
        None
    """
    # Parse user arguments once.
    args = parse_arguments()

    try:
        # Resolve target project and initialize config directory variables.
        selected_dir = select_project_dir()
        config.setup_directories(selected_dir)

        # Resolve starter options.
        kind = normalize_kind(args.kind)
        
        # Keep separate TB description to support DUT-derived testbench metadata.
        tb_description = ""
        design_ext = "sv"

        # Testbench-only flow: target an existing DUT and auto-derive metadata.
        if kind == "testbench":
            # Ask for DUT module name used for instantiation.
            module_name = input("DUT module name for testbench [No response is treated as MyModule]: ").strip()
            module_name = module_name if module_name else "MyModule"

            # Try to locate DUT source in designs directory.
            dut_path = find_dut_file(module_name)
            if dut_path is None:
                raise FileNotFoundError(
                    f"Could not find DUT file for '{module_name}' in {config.DESIGNS_DIR}."
                )

            # Parse DUT ports so TB signals/instantiation match the DUT interface.
            ports = parse_ports_from_dut(module_name, dut_path)

            # Derive TB description from DUT description.
            dut_description = extract_dut_description(dut_path)
            tb_description = make_testbench_description(module_name, dut_description)

            # Keep generic design description unused in testbench-only mode.
            description = "not used in testbench-only mode."
        else:
            # Prompt for module name with quick default.
            module_name = input("Module name [No response is treated as MyModule]: ").strip()
            module_name = module_name if module_name else "MyModule"

            # Ask user for design file extension when DUT generation is requested.
            design_ext = choose_design_extension()

            # Prompt for optional description with quick default.
            description_text = input(
                "Description [No response is treated as 'Implements core DUT functionality.']: "
            ).strip()
            description = (
                description_text if description_text else "Implements core DUT/Testbench functionality."
            )

            # Parse ports using one prompt for each direction.
            input_line = input(
                "Input ports (optional, comma-separated). Forms: name | name:width | type:name | type:name:width. No response is treated as no input ports.\n> "
            ).strip()
            output_line = input(
                "Output ports (optional, comma-separated). Forms: name | name:width | type:name | type:name:width. No response is treated as no output ports.\n> "
            ).strip()
            inout_line = input(
                "Inout ports (optional, comma-separated). Forms: name | name:width | type:name | type:name:width. No response is treated as no inout ports.\n> "
            ).strip()

            # Parse and merge ports while preserving prompt order.
            input_ports = parse_ports_compact(input_line, "input") if input_line else []
            output_ports = parse_ports_compact(output_line, "output") if output_line else []
            inout_ports = parse_ports_compact(inout_line, "inout") if inout_line else []
            ports = input_ports + output_ports + inout_ports

        # Build requested output files and render content.
        outputs = build_outputs(
            module_name,
            kind,
            description,
            ports,
            tb_description=tb_description,
            design_ext=design_ext,
        )

        # Write all outputs and track whether any file was actually written.
        wrote_any = False
        for output_path, content in outputs:
            wrote_any = write_file(output_path, content) or wrote_any

        # If everything was skipped (for example, existing files without --force), exit non-zero.
        if not wrote_any:
            sys.exit(1)
    except (FileNotFoundError, ValueError) as error:
        # Print user-facing error and terminate cleanly.
        print(error)
        sys.exit(1)


if __name__ == "__main__":
    main()
